CarInfoManagement/Controllers/UserAuthenticationController.cs
using CarInfoBFF.Identity;
using CarInfoManagement.Models.AuthendicationModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CarInfoManagement.Controllers
{
    public class UserAuthenticationController : Controller
    {
        private IIdentityService authService;
        public UserAuthenticationController(IIdentityService authService)
        {
            this.authService = authService;
        }
        [HttpGet]
        public async Task<IActionResult> Register()
        {
            List<SelectListItem> option = new List<SelectListItem>();
            option = new List<SelectListItem>
            {
                new SelectListItem{Value="Admin",Text = "Admin"},
                new SelectListItem {Value = "User", Text = "User"}
            };
            ViewBag.role = option;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(RegistrationModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
            var result = await authService.RegisterAsync(model);
            if (result.statusCode == 1)
                return RedirectToAction(nameof(Login));
            else
            {
                TempData["msg"] = result.message;
                return RedirectToAction(nameof(Login));
            }
        }
        [HttpGet]
        public async Task<IActionResult> Login()
        {
            
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var result = await authService.LoginAsync(model);
            
           
            if (result !=null && result.statusCode == 1)
            {
                HttpContext.Session.SetString("Role", result.role);
                HttpContext.Session.SetString("AccessToken", result.token);
                TempData["Role"] = HttpContext.Session.GetString("Role");
                return RedirectToAction("Index", "Home");
            }
            else
            {
                TempData["msg"] = "Could not logged in. Please check User Name or Password";
                return RedirectToAction(nameof(Login));
            }
        }

        public async Task<IActionResult> Logout()
        {
            HttpContext.Session.Remove("Role");
            HttpContext.Session.Remove("AccessToken");
            TempData["Role"] = null;
            //await authService.LogoutAsync();
            return RedirectToAction(nameof(Login));
        }
    }
}

CarInfoManagement/Views/UserAuthentication/Login.cshtml
@model CarInfoManagement.Models.AuthendicationModel.LoginModel
@{
}

<form class="w-40" asp-action="Login" method="post">
    <h2 class="pb-10">Login</h2>
    <div class="input-container">
        <label asp-for="userName" class="w-40">User Name</label>
        <input type="text" class="input" asp-for="userName">
    </div>
    <div class="message-box pd-x-28 error">
        <span asp-validation-for="userName"></span>
    </div>


    <div class="input-container">
        <label asp-for="password" class="w-40">Password</label>
        <input type="password" class="input" asp-for="password">
    </div>
    <div class="message-box pd-x-28 error">
        <span asp-validation-for="password"></span>
    </div>
   


    @if (TempData["msg"] != null)
    {
            <div class="alert mb-1">
            @TempData["msg"]
        </div>
    }

    <div class="input-container">
        <button class="btn btn-default" type="submit">Login</button> <button class="btn btn-sec" type="button" onclick="location.href='@Url.Action("Register", "UserAuthentication")'">Sign Up</button>
    </div>
</form>
<div></div>

CarInfoManagement/Views/UserAuthentication/Register.cshtml
@model CarInfoManagement.Models.AuthendicationModel.RegistrationModel
@{
}

<form class="w-40" asp-action="Register" method="post">
    <h2 class="pb-10">Register</h2>
    <div class="input-container">
        <label asp-for="Name" class="w-40">Name</label>
        <input type="text" class="input" asp-for="Name">
    </div>
    <div class="message-box pd-x-28 error">
        <span asp-validation-for="Name"></span>
    </div>


    <div class="input-container">
        <label asp-for="Email" class="w-40">Email</label>
        <input type="text" class="input" asp-for="Email">
    </div>
    <div class="message-box pd-x-28 error">
        <span asp-validation-for="Email"></span>
    </div>

    <div class="input-container">
        <label asp-for="Username" class="w-40">Username</label>
        <input type="text" class="input" asp-for="Username">
    </div>
    <div class="message-box pd-x-28 error">
        <span asp-validation-for="Username"></span>
    </div>

    <div class="input-container">
        <label asp-for="Password" class="w-40">Password</label>
        <input type="password" class="input" asp-for="Password">
    </div>
    <div class="message-box pd-x-28 error">
        <span asp-validation-for="Password"></span>
    </div>

    <div class="input-container">
    <label asp-for="Role" class="w-40">Role</label>
        <select asp-for="Role" asp-items="ViewBag.role"></select>
    </div>
    <div class="message-box pd-x-28 error">
        <span asp-validation-for="Role"> </span>
    </div>


    @if (TempData["msg"] != null)
    {
        <div class="alert mb-1">
            @TempData["msg"]
        </div>
    }

    <div class="input-container">
        <button class="btn btn-default" type="submit">Sign Up </button>
        @*<a class="btn btn-sec" href="#">Add more</a>*@
    </div>
</form>